apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gocd-agent
  labels:
    app: gocd
    component: agent
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: gocd
        component: agent
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: gocd-agent
        image: "maazghani/gocd-agent:v1"
        imagePullPolicy: IfNotPresent
        env:
        - name: GO_SERVER_URL
          value: "https://gocd-server:8154/go/"
        - name: DOCKER_HOST 
          value: tcp://localhost:2375 
        volumeMounts:
        - name: agent-config
          mountPath: /tmp
        - name: goagent-home
          mountPath: /home/go
        - name: kubeconfig
          mountPath: /home/go/.kube
      - name: dind-daemon 
        image: "docker:1.12.6-dind" 
        imagePullPolicy: IfNotPresent
        env:
        resources:
          requests:
            cpu: 20m
            memory: 512Mi
        securityContext: 
          privileged: true
        volumeMounts: 
        - name: docker-storage
          mountPath: /var/lib/docker
      volumes:
      - name: agent-config
        configMap:
          name: gocd-agent-autoregister
          items:
          - key: autoregister.properties
            path: autoregister.properties
      - name: goagent-home
        emptyDir: {}
      - name: docker-storage 
        emptyDir: {}
