apiVersion: v1
kind: Service
metadata:
  name: gocd-server
  labels:
    app: gocd
    component: server
spec:
  ports:
  - name: http
    port: 8153
    targetPort: 8153
    protocol: TCP
  - name: https
    port: 8154
    targetPort: 8154
    protocol: TCP
  - name: ingress
    port: 443
    targetPort: 8154
    protocol: TCP
  selector:
    app: gocd
    component: server
